from config.config_path_variables import * 

# Dossiers importants
print('LOG_FOLDER =', LOG_FOLDER)
print('CONFIG =', CONFIG)
print('IMG_SRC =', IMG_SRC)
print('DOSSIER_FOURNISSEURS =', DOSSIER_FOURNISSEURS)
print('DOSSIER_PLATFORMS =', DOSSIER_PLATFORMS)
print('UPDATED_FILES_PATH_RACINE =', UPDATED_FILES_PATH_RACINE)
print('UPDATED_FILES_PATH =', UPDATED_FILES_PATH)
print('VERIFIED_FILES_PATH =', VERIFIED_FILES_PATH)


# Fichiers YAML
print('HEADER_PLATFORMS_YAML =', HEADER_PLATFORMS_YAML)
print('HEADER_FOURNISSEURS_YAML =', HEADER_FOURNISSEURS_YAML) 
print('YAML_ENCODING_SEP_FILE_PATH =', YAML_ENCODING_SEP_FILE_PATH)